# Generated by Django 5.0.4 on 2026-04-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentteam',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='teamevent',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='teamtask',
            options={'ordering': ['priority', 'created_at', 'id']},
        ),
    ]
