# Generated by Django 5.0.4 on 2026-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_agentteam_options_alter_teamevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtask',
            options={'ordering': ['-priority', 'created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2),
        ),
    ]
