# Generated by Django 5.0.4 on 2026-04-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teamtask_options_alter_teamtask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamevent',
            name='event_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_started', 'Task Started'), ('task_completed', 'Task Completed'), ('task_blocked', 'Task Blocked'), ('task_unblocked', 'Task Unblocked'), ('pr_opened', 'PR Opened'), ('pr_merged', 'PR Merged'), ('review_completed', 'Review Completed'), ('agent_joined', 'Agent Joined'), ('agent_left', 'Agent Left'), ('mission_started', 'Mission Started'), ('mission_completed', 'Mission Completed')], max_length=30),
        ),
    ]
