# Generated by Django 5.0.4 on 2026-04-03 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_teamevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField(help_text='Full prompt content in markdown')),
                ('target_repo', models.CharField(help_text='e.g., kkwills13/nock-command-center', max_length=200)),
                ('target_branch_prefix', models.CharField(default='feature/', help_text='Branch prefix for the build', max_length=100)),
                ('complexity', models.CharField(choices=[('quick', 'Quick Task'), ('standard', 'Standard Build'), ('deep', 'Deep Build')], default='standard', max_length=20)),
                ('estimated_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('priority', models.IntegerField(default=50, help_text='1-100, higher = more urgent')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('author', models.CharField(default='mara', max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('executed_by', models.CharField(blank=True, max_length=100)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True, max_length=500)),
                ('execution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on_prompts', models.ManyToManyField(blank=True, related_name='blocked_by', to='teams.promptfile')),
                ('team_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt', to='teams.teamtask')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('success', 'Success'), ('review_requested', 'Changes Requested'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], max_length=20, null=True)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True, max_length=500)),
                ('review_cycles', models.IntegerField(default=0, help_text='How many review-fix cycles')),
                ('max_review_cycles', models.IntegerField(default=3, help_text='Stop after this many cycles')),
                ('notes', models.TextField(blank=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='teams.promptfile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
