# Generated by Django 5.0.4 on 2026-04-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_prompt_queue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptexecution',
            options={'ordering': ['-started_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='promptfile',
            options={'ordering': ['-priority', 'created_at', 'id']},
        ),
    ]
