# Generated by Django 5.0.4 on 2026-04-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_prompt_ordering_fix'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentteam',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_teams', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='promptexecution',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_executions', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='promptfile',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_files', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='teamevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_events', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_tasks', to='workspaces.workspace'),
        ),
    ]
