# Generated by Django 5.0.4 on 2026-03-14 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pr_id', models.BigIntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], max_length=10)),
                ('coderabbit_status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('ci_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('tests_passed', models.IntegerField(blank=True, null=True)),
                ('tests_failed', models.IntegerField(blank=True, null=True)),
                ('files_changed', models.IntegerField(default=0)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('opened_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('generating_agent', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('github_id', models.BigIntegerField(unique=True)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('webhook_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pipeline.pullrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='pipeline.repository'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'number')},
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_commit_sha', models.CharField(max_length=40)),
                ('last_commit_message', models.TextField(blank=True)),
                ('last_commit_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='pipeline.repository')),
            ],
            options={
                'verbose_name_plural': 'branches',
                'unique_together': {('repository', 'name')},
            },
        ),
    ]
