# Generated by Django 5.0.4 on 2026-03-14 13:38

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='repository',
            name='webhook_secret',
            field=fernet_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('repository', 'name'), name='unique_repository_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('repository', 'number'), name='unique_repository_pr_number'),
        ),
    ]
