# Generated by Django 5.0.4 on 2026-03-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_alter_branch_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='github_pr_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
