# Generated by Django 5.0.4 on 2026-03-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_alter_pullrequest_github_pr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(db_index=True, max_length=100)),
                ('ref', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_events', to='pipeline.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='branchevent',
            constraint=models.UniqueConstraint(fields=('repository', 'delivery_id'), name='unique_branch_event_delivery'),
        ),
    ]
