# Generated by Django 5.0.4 on 2026-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_branchevent_branchevent_unique_branch_event_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevent',
            name='delivery_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='prevent',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery_id', ''), _negated=True), fields=('delivery_id',), name='unique_pr_event_delivery_id'),
        ),
    ]
