# Generated by Django 6.0.3 on 2026-03-14 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_prevent_delivery_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
