# Generated by Django 5.0.4 on 2026-03-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_alter_prevent_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_repository_owner_name'),
        ),
    ]
