# Generated by Django 5.0.4 on 2026-04-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_unique_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=200)),
                ('pr_number', models.IntegerField()),
                ('pr_title', models.CharField(max_length=500)),
                ('pr_url', models.URLField(max_length=500)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('reviewer', models.CharField(choices=[('coderabbit', 'CodeRabbit'), ('copilot', 'GitHub Copilot'), ('gemini', 'Gemini'), ('human', 'Human'), ('ci', 'CI Check')], max_length=20)),
                ('reviewer_login', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('commented', 'Commented'), ('success', 'CI Success'), ('failure', 'CI Failure'), ('neutral', 'CI Neutral')], max_length=20)),
                ('body_preview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
