# Generated by Django 5.0.4 on 2026-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_review_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewalert',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='reviewalert',
            name='pr_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reviewalert',
            name='repo',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
