# Generated by Django 5.0.4 on 2026-04-04 18:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_review_alert_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewalert',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workflow_id', models.CharField(db_index=True, help_text='Matches workflow_id from .workflow-state.json', max_length=200)),
                ('repo', models.CharField(db_index=True, help_text='e.g., nock-command-center, claude-terminal, project-nexus', max_length=100)),
                ('category', models.CharField(choices=[('prompt', 'Prompt Queue'), ('build', 'Build'), ('test', 'Test'), ('lint', 'Lint/Quality'), ('git', 'Git Operations'), ('pr', 'Pull Request'), ('review', 'Code Review'), ('review_fix', 'Review Fix'), ('ticket', 'Ticket'), ('escalation', 'Escalation'), ('pipeline', 'Pipeline Control'), ('session', 'Session'), ('checkpoint', 'Checkpoint'), ('close', 'Session Close'), ('notification', 'Notification'), ('error', 'Error')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(help_text="Short description: 'PR #48 opened on nock-command-center'", max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('lane', models.CharField(choices=[('prompt', 'Prompt Queue (Lane 1)'), ('ticket', 'Ticket Queue (Lane 2)'), ('audit', 'Periodic Audit'), ('manual', 'Manual Operation')], default='manual', max_length=10)),
                ('agent', models.CharField(choices=[('kit', 'Kit (Claude Code)'), ('codex', 'Codex (OpenAI)'), ('coderabbit', 'CodeRabbit'), ('copilot', 'Copilot'), ('gemini', 'Gemini'), ('mara', 'Mara'), ('system', 'NockCC System')], default='kit', max_length=15)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, default='', max_length=200)),
                ('asana_task_id', models.CharField(blank=True, default='', max_length=50)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='How long this step took', null=True)),
                ('token_count', models.IntegerField(blank=True, help_text='Tokens consumed for this step', null=True)),
                ('files_changed', models.IntegerField(blank=True, help_text='Number of files created or modified', null=True)),
                ('test_count', models.IntegerField(blank=True, help_text='Number of tests after this step', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id', '-created_at'], name='idx_event_wf_ts'), models.Index(fields=['repo', '-created_at'], name='idx_event_repo_ts'), models.Index(fields=['category', 'severity'], name='idx_event_cat_sev')],
            },
        ),
    ]
