# Generated by Django 5.0.4 on 2026-04-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_register_nocktechnologies_repos'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='branchevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_events', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='pipelineevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_events', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='prevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_events', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='repository',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='reviewalert',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_alerts', to='workspaces.workspace'),
        ),
    ]
