# Generated by Django 5.0.4 on 2026-03-14 21:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0006_alter_prevent_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('claude_code', 'Claude Code'), ('codex', 'Codex Desktop'), ('copilot', 'GitHub Copilot'), ('gemini', 'Gemini'), ('kimi', 'Kimi'), ('chatgpt', 'ChatGPT'), ('claude_chat', 'Claude Chat'), ('other', 'Other')], max_length=50)),
                ('machine', models.CharField(choices=[('windows', 'Windows Primary'), ('mac', 'Mac Secondary'), ('other', 'Other')], default='mac', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('task_description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('tokens_input', models.BigIntegerField(default=0)),
                ('tokens_output', models.BigIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('commits_generated', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('pr_generated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generating_session', to='pipeline.pullrequest')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='pipeline.repository')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agent_sessions.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
