# Generated by Django 5.0.4 on 2026-03-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(default='mac', max_length=50)),
                ('sessions', models.JSONField(default=list, help_text='Array of active session states from Terminal')),
                ('active_ports', models.JSONField(default=list, help_text='Array of port numbers detected by Terminal')),
                ('terminal_version', models.CharField(blank=True, max_length=50)),
                ('received_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'terminal heartbeat',
                'verbose_name_plural': 'terminal heartbeats',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('tracking', 'Tracking')], default='active', max_length=20),
        ),
    ]
