# Generated by Django 5.0.4 on 2026-03-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0002_terminalheartbeat_alter_agentsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalheartbeat',
            name='machine',
            field=models.CharField(default='mac', max_length=50, unique=True),
        ),
    ]
