# Generated by Django 5.0.4 on 2026-04-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0003_alter_terminalheartbeat_machine'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='terminalheartbeat',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_heartbeats', to='workspaces.workspace'),
        ),
    ]
