# Generated by Django 5.0.4 on 2026-03-15 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0007_unique_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('claude_md', 'CLAUDE.md'), ('architecture', 'Architecture Doc'), ('skill_file', 'Skill File'), ('design_doc', 'Design Document'), ('changelog', 'Changelog'), ('master_ref', 'Master Reference'), ('other', 'Other')], max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('last_content_hash', models.CharField(blank=True, max_length=64)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('line_count', models.IntegerField(default=0)),
                ('is_stale', models.BooleanField(default=False)),
                ('staleness_threshold_days', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_docs', to='pipeline.repository')),
            ],
            options={
                'ordering': ['repository', 'file_path'],
            },
        ),
        migrations.CreateModel(
            name='ContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=64)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('line_count', models.IntegerField(default=0)),
                ('diff_summary', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='context.contextdocument')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='contextdocument',
            constraint=models.UniqueConstraint(fields=('repository', 'file_path'), name='unique_context_doc_repo_path'),
        ),
    ]
