# Generated by Django 5.0.4 on 2026-04-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextsnapshot',
            options={'ordering': ['-captured_at', '-pk']},
        ),
    ]
