# Generated by Django 5.0.4 on 2026-04-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_alter_contextsnapshot_options'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextdocument',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_documents', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='contextsnapshot',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_snapshots', to='workspaces.workspace'),
        ),
    ]
