# Generated by Django 5.0.4 on 2026-03-16 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='remote.commandrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
