# Generated by Django 5.0.4 on 2026-03-17 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        ('vault', '0002_alter_document_category_alter_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklymemo',
            name='vault_document_id',
        ),
        migrations.AddField(
            model_name='advisorconversation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklymemo',
            name='vault_document',
            field=models.ForeignKey(blank=True, help_text='Document saved in the vault', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.document'),
        ),
        migrations.AddConstraint(
            model_name='predictivealert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_resolved', False)), fields=('category', 'title'), name='unique_active_alert_per_category_title'),
        ),
        migrations.AddConstraint(
            model_name='weeklymemo',
            constraint=models.UniqueConstraint(fields=('week_start', 'week_end'), name='unique_memo_per_week'),
        ),
    ]
