# Generated by Django 5.0.4 on 2026-04-03 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_remove_weeklymemo_vault_document_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartWatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('condition_type', models.CharField(choices=[('pr_waiting', 'PR Waiting for Review'), ('session_long', 'Session Running Long'), ('task_due_tomorrow', 'Task Due Tomorrow'), ('context_high', 'Context % High'), ('brain_stale', 'Brain Entry Stale'), ('no_activity', 'No Activity in Period'), ('custom', 'Custom')], max_length=30)),
                ('threshold_minutes', models.IntegerField(default=240, help_text='Threshold in minutes for time-based rules')),
                ('threshold_value', models.IntegerField(default=75, help_text='Threshold value for percentage-based rules')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message_template', models.TextField(default='⚠️ Smart Watch alert: {name}', help_text='Message template. Variables: {pr_number}, {repo}, {branch}, {project}, {task_name}, {value}, {threshold}')),
                ('enabled', models.BooleanField(default=True)),
                ('send_telegram', models.BooleanField(default=True)),
                ('send_slack', models.BooleanField(default=False)),
                ('cooldown_minutes', models.IntegerField(default=60, help_text="Don't re-alert for the same condition within this window")),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SmartWatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='intelligence.smartwatchrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
