# Generated by Django 5.0.4 on 2026-04-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_smart_watch_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartwatchrule',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
