# Generated by Django 5.0.4 on 2026-04-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('relationship', 'Relationship'), ('domain', 'Domain'), ('decision', 'Decision'), ('project', 'Project'), ('personal', 'Personal'), ('lesson', 'Lesson'), ('tool', 'Tool')], max_length=20)),
                ('confidence', models.CharField(choices=[('observed', 'Observed'), ('inferred', 'Inferred'), ('stale', 'Stale')], default='observed', max_length=20)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'key'],
                'unique_together': {('key', 'category')},
            },
        ),
    ]
