# Generated by Django 5.0.4 on 2026-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_seed_memory_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('entries_reviewed', models.IntegerField(default=0)),
                ('entries_promoted', models.IntegerField(default=0)),
                ('entries_archived', models.IntegerField(default=0)),
                ('entries_pruned', models.IntegerField(default=0)),
                ('contradictions_resolved', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='memoryentry',
            name='category',
            field=models.CharField(choices=[('identity', 'Identity'), ('relationship', 'Relationship'), ('domain', 'Domain'), ('decision', 'Decision'), ('project', 'Project'), ('personal', 'Personal'), ('lesson', 'Lesson'), ('tool', 'Tool'), ('continuity', 'Continuity')], max_length=20),
        ),
    ]
