# Generated by Django 5.0.4 on 2026-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_morning_note_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('private', 'Private'), ('design', 'Design'), ('handoff', 'Handoff'), ('in_chat', 'In-Chat Handoff')], max_length=20)),
                ('source', models.CharField(choices=[('asana_v1', 'Asana Volume 1'), ('asana_v2', 'Asana Volume 2'), ('nockcc', 'NockCC Brain'), ('cowork', 'Cowork'), ('api', 'API')], default='nockcc', max_length=20)),
                ('entry_date', models.DateTimeField()),
                ('session_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asana_comment_gid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('search_vector', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Diary Entry',
                'verbose_name_plural': 'Diary Entries',
                'ordering': ['-entry_date'],
                'indexes': [models.Index(fields=['-entry_date'], name='brain_diary_entry_d_5ad674_idx'), models.Index(fields=['category'], name='brain_diary_categor_415371_idx'), models.Index(fields=['session_date'], name='brain_diary_session_ed307f_idx'), models.Index(fields=['source'], name='brain_diary_source_d4db30_idx'), models.Index(fields=['asana_comment_gid'], name='brain_diary_asana_c_f0a972_idx')],
            },
        ),
    ]
