# Generated by Django 5.0.4 on 2026-04-10 13:14

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    """Enable pgvector extension on PostgreSQL; no-op elsewhere (e.g. SQLite tests)."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


def drop_vector_extension(apps, schema_editor):
    # Leave the extension in place on reverse — other tables may depend on it.
    pass


def create_embedding_index(apps, schema_editor):
    """Create an ivfflat index for fast cosine-distance search on PostgreSQL."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS research_chunk_embedding_idx "
            "ON brain_researchchunk USING ivfflat (embedding vector_cosine_ops) "
            "WITH (lists = 50)"
        )


def drop_embedding_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX IF EXISTS research_chunk_embedding_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_morning_note_sent'),
    ]

    operations = [
        migrations.RunPython(create_vector_extension, drop_vector_extension),
        migrations.CreateModel(
            name='ResearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Derived from file path: raw-research-abl-underwriting-overview', max_length=200, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('source_path', models.CharField(help_text='Original vault path: raw/research/abl-underwriting/overview.md', max_length=500)),
                ('source_type', models.CharField(choices=[('research', 'Kimi Research'), ('wiki', 'Wiki Summary'), ('article', 'Article'), ('transcript', 'Transcript')], max_length=20)),
                ('topic', models.CharField(help_text='Topic directory: abl-underwriting, factoring-pricing, etc.', max_length=200)),
                ('content', models.TextField(help_text='Full document content')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('file_hash', models.CharField(help_text='SHA-256 of file content for change detection', max_length=64)),
                ('is_indexed', models.BooleanField(default=False, help_text='True when all chunks have embeddings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['topic', 'title'],
                'indexes': [
                    models.Index(fields=['topic'], name='brain_resea_topic_e23349_idx'),
                    models.Index(fields=['source_type'], name='brain_resea_source__29d471_idx'),
                    models.Index(fields=['is_indexed'], name='brain_resea_is_inde_00e088_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ResearchChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(help_text='Position of this chunk in the document (0-based)')),
                ('content', models.TextField(help_text='The chunk text')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='OpenAI text-embedding-3-small vector', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Optional metadata: headings, section context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='brain.researchdocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.RunPython(create_embedding_index, drop_embedding_index),
    ]
