# Generated by Django 5.0.4 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_diary_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={
                'ordering': ['-entry_date'],
                'verbose_name': 'Diary Entry',
                'verbose_name_plural': 'Diary Entries',
            },
        ),
        migrations.RemoveIndex(
            model_name='diaryentry',
            name='brain_diary_asana_c_f0a972_idx',
        ),
    ]
