# Generated by Django 5.0.4 on 2026-04-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_research_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('cortextos-agent', 'CortexTOS Agent'), ('claude-chat', 'Claude Chat'), ('kit-session', 'Kit Session'), ('codex-session', 'Codex Session')], help_text='Which session origin this handoff describes — one active handoff per context.', max_length=30, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(help_text="Narrative — what's happening, what shipped, what's next, technical state.")),
                ('action_items', models.JSONField(blank=True, default=list, help_text='List of {description, status: open|completed|deferred, reason: null|string}.')),
                ('previous_items_resolved', models.BooleanField(default=False, help_text="Was the previous handoff's action items checked before this overwrite?")),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Handoff Entry',
                'verbose_name_plural': 'Handoff Entries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('previous_items_resolved', models.BooleanField(default=False)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='brain.handoffentry')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('handoff', 'version')},
            },
        ),
    ]
