# Generated by Django 5.0.4 on 2026-04-10 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0007_fix_diary_entry_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-safe identifier: mara-core, kevin-core, fuzzy', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='The full document content (markdown)')),
                ('version', models.PositiveIntegerField(default=1)),
                ('document_type', models.CharField(choices=[('core_identity', 'Core Identity'), ('partner_identity', 'Partner Identity'), ('operational', 'Operational'), ('framework', 'Framework')], max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete only — never hard delete identity docs')),
                ('load_order', models.PositiveIntegerField(default=0, help_text='Order for boot endpoint: lower = loaded first')),
                ('updated_by', models.CharField(default='system', help_text='Which instance/session updated this', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['load_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('document_type', models.CharField(max_length=20)),
                ('updated_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='brain.identitydocument')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('document', 'version')},
            },
        ),
    ]
