# Generated by Django 5.0.4 on 2026-03-15 01:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpendBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('budget_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alert_threshold_pct', models.IntegerField(default=80)),
                ('alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('google', 'Google'), ('github', 'GitHub'), ('other', 'Other')], max_length=50)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('renewal_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UsagePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model', models.CharField(max_length=100)),
                ('workspace', models.CharField(blank=True, max_length=255)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('cache_read_tokens', models.BigIntegerField(default=0)),
                ('cache_write_tokens', models.BigIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('request_count', models.IntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'model'],
            },
        ),
        migrations.AddConstraint(
            model_name='usageperiod',
            constraint=models.UniqueConstraint(fields=('date', 'model', 'workspace'), name='unique_usage_period_date_model_workspace'),
        ),
    ]
