# Generated by Django 5.0.4 on 2026-03-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendbudget',
            name='month',
            field=models.DateField(unique=True),
        ),
    ]
