# Generated by Django 5.0.4 on 2026-03-17 03:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0002_unique_budget_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('software', 'Software & Dev Tools'), ('hardware', 'Hardware'), ('infrastructure', 'Infrastructure'), ('domains', 'Domains & Branding'), ('formation', 'Business Formation'), ('legal', 'Legal & Professional'), ('other', 'Other')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_refund', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('amex_1009', 'Amex -1009 (Delta SkyMiles)'), ('visa_5540', 'Visa -5540'), ('amex_8515', 'Amex -8515'), ('stripe_link', 'Link (Stripe)'), ('paypal_cap1', 'PayPal → Capital One ••2250'), ('paypal', 'PayPal (kkwills13@gmail.com)'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', 'vendor'],
            },
        ),
        migrations.AlterField(
            model_name='subscriptiontracker',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('google', 'Google'), ('github', 'GitHub'), ('vercel', 'Vercel'), ('coderabbit', 'CodeRabbit'), ('asana', 'Asana'), ('moonshot', 'Moonshot AI'), ('zoho', 'ZOHO'), ('railway', 'Railway'), ('other', 'Other')], max_length=50),
        ),
    ]
