# Generated by Django 5.0.4 on 2026-03-17 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0003_add_expense_model_and_subscription_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('consulting', 'Nock Consulting'), ('academy', 'Nock Academy (Gumroad)'), ('licensing', 'Nexus Licensing'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', 'source'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
