# Generated by Django 5.0.4 on 2026-03-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0006_alter_prevent_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asana_gid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AsanaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asana_gid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('section_name', models.CharField(blank=True, max_length=255)),
                ('assignee_name', models.CharField(blank=True, max_length=255)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('notes_preview', models.TextField(blank=True)),
                ('permalink_url', models.URLField(blank=True, max_length=500)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('asana_updated_at', models.DateTimeField(blank=True, null=True)),
                ('linked_pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tasks', to='pipeline.pullrequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='asana_tasks.asanaproject')),
            ],
            options={
                'ordering': ['due_on', '-priority'],
            },
        ),
    ]
