# Generated by Django 5.0.4 on 2026-04-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asanatask',
            name='last_comment_gid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
