# Generated by Django 5.0.4 on 2026-04-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana_tasks', '0002_add_last_comment_gid'),
    ]

    operations = [
        migrations.AddField(
            model_name='asanatask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete timestamp set when task is deleted via the write-back API.', null=True),
        ),
        migrations.CreateModel(
            name='AsanaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asana_gid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='asana_tasks.asanaproject')),
            ],
            options={
                'ordering': ['project__name', 'order', 'name'],
            },
        ),
    ]
