# Generated by Django 5.0.4 on 2026-04-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana_tasks', '0003_asanatask_deleted_at_asanasection'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asanaproject',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asana_projects', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='asanasection',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asana_sections', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='asanatask',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asana_tasks', to='workspaces.workspace'),
        ),
    ]
