# Generated by Django 5.0.4 on 2026-03-17 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('formation', 'Business Formation'), ('legal', 'Legal & Contracts'), ('financial', 'Financial'), ('insurance', 'Insurance'), ('tax', 'Tax Documents'), ('trademark', 'Trademark & IP'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='vault/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('filename', models.CharField(max_length=200)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
