# Generated by Django 5.0.4 on 2026-03-17 15:52

import django.core.validators
import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('formation', 'Business Formation'), ('legal', 'Legal & Contracts'), ('financial', 'Financial'), ('insurance', 'Insurance'), ('tax', 'Tax Documents'), ('trademark', 'Trademark & IP'), ('reports', 'Reports & Memos'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='vault/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx', 'xls', 'xlsx']), vault.models.validate_file_size]),
        ),
    ]
