# Generated by Django 5.0.4 on 2026-03-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_document_category_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(help_text='Markdown content of the session report')),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('captured_at', models.DateTimeField(help_text='When Terminal captured this report')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.CharField(default='mac', max_length=50)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
