# Generated by Django 5.0.4 on 2026-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='trigger_event',
            field=models.CharField(choices=[('pr_merged', 'PR Merged'), ('pr_opened', 'PR Opened'), ('ci_failed', 'CI Failed'), ('ci_passed', 'CI Passed'), ('coderabbit_approved', 'CodeRabbit Approved'), ('coderabbit_changes_requested', 'CodeRabbit Changes Requested'), ('push', 'Push'), ('asana_comment', 'Asana Comment'), ('budget_threshold', 'Budget Threshold'), ('context_stale', 'Context Stale'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended')], max_length=50),
        ),
    ]
