# Generated by Django 5.0.4 on 2026-04-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationrule_trigger_event'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_channels', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='workspaces.workspace'),
        ),
    ]
